# These are supported funding model platforms

# github: easy-node-pro # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
#patreon: # Replace with a single Patreon username
# open_collective: easynodepro # Replace with a single Open Collective username
# ko_fi: easynodepro
#tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
#community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
# liberapay: easynode # Replace with a single Liberapay username
#issuehunt: # Replace with a single IssueHunt username
#otechie: # Replace with a single Otechie username
custom: ['https://mee6.xyz/en/m/easynode', 'https://bit.ly/easydonatecrypto'] # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']